name: jainverse
description: Jain Verse Video Audio.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  chewie: ^1.7.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0
  we_slide: ^2.4.0

  # Media & Audio
  audio_service: ^0.18.18
  audio_session: ^0.1.25
  just_audio: ^0.9.46
  flutter_tts: ^4.2.3
  # youtube_api: ^1.0.4
  youtube_player_flutter: ^9.1.1
  volume_controller: ^2.0.7

  # State Management
  provider: ^6.1.1
  session_storage: ^0.0.1
  synchronized: ^3.3.1

  # Network & API
  dio: ^5.4.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.0

  # Data Persistence
  floor: ^1.4.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5

  # Utilities
  # flutter_share: ^2.0.0
  share_plus: ^11.0.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  intl: ^0.20.2
  iphone_has_notch: ^1.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.3.0

  # Content Display
  flutter_widget_from_html: ^0.15.3
  flutter_svg: ^2.0.9

  # Color Extraction (material_color_utilities is bundled with Flutter)

  # In-App Purchases & Payments
  in_app_purchase: ^3.2.3
  # flutter_paypal: ^0.2.1
  # flutter_paystack: ^1.0.7
  flutter_stripe: ^11.5.0
  # razorpay_flutter: ^1.3.5

  # Advertisements
  google_mobile_ads: ^6.0.0

  # App Updates
  upgrader: ^11.4.0

  # Web platform compatibility
  device_info_plus: ^11.4.0
  wakelock_plus: ^1.3.2
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.22.0
  video_player_web: ^2.3.5
  image_picker_for_web: ^3.0.1
  # paystack_flutter_sdk: ^0.0.1-alpha.2
  in_app_purchase_storekit: ^0.4.2
  foundation: ^0.0.5
  rxdart: ^0.27.7
  sqflite: ^2.4.2
  just_audio_web: ^0.4.16
  shared_preferences_web: ^2.4.3
  url_launcher_web: ^2.4.1
  flutter_screenutil: ^5.9.0
  permission_handler: ^12.0.1

  audio_service_web: any
  animations: ^2.0.11
  image: ^4.0.17
  video_player: ^2.8.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^5.0.0

  # Build Tools
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  floor_generator: ^1.4.2
  dependency_validator: ^3.2.3

# App Icon Configuration
flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/logo.png
    - assets/images/SuccessfullysetBackground.jpg
    - assets/images/default_screen.jpg
    - assets/images/placeholder.png
    - assets/images/Camera.png
    - assets/images/Cancel.png
    - assets/images/Gallery.png
    - assets/images/logo-transparent.png
    - assets/images/music-note-illustrator.png
    - assets/images/onboard_bg_1.png
    - assets/images/onboard_bg_2.png
    - assets/images/onboard_bg_3.png
    - assets/images/onboard_bg_4.png
    - assets/images/onboard_bg_5.png
    - assets/images/JainVerse-Logo-Main.png
    - assets/images/discover_active.svg
    - assets/images/discover_inactive.svg
    - assets/images/library_active.svg
    - assets/images/library_inactive.svg
    - assets/images/profile_active.svg
    - assets/images/profile_inactive.svg
    - assets/images/search_active.svg
    - assets/images/search_inactive.svg
    - assets/images/global.svg
    - assets/images/playlist_placeholder.png
    - assets/images/song_placeholder.png

    # Icons
    - assets/icons/person.png
    - assets/icons/stripe.png
    - assets/icons/paystack.png
    - assets/icons/razorpay.png
    - assets/icons/paypal.png
    - assets/icons/blog.png
    - assets/icons/lock.png
    - assets/icons/eyeshow.png
    - assets/icons/hide.png
    - assets/icons/email.png
    - assets/icons/threedots.png
    - assets/icons/discovericon.png
    - assets/icons/artisticon.png
    - assets/icons/album.png
    - assets/icons/stations.png
    - assets/icons/downloadicon.png
    - assets/icons/fav.png
    - assets/icons/favfill.png
    - assets/icons/fav2.png
    - assets/icons/repeat.png
    - assets/icons/history.png
    - assets/icons/user2.png
    - assets/icons/pencil.png
    - assets/icons/mobile.png
    - assets/icons/iconoverview.png
    - assets/icons/dropdown.png
    - assets/icons/search.png
    - assets/icons/mic.png
    - assets/icons/music.png
    - assets/icons/adver.png
    - assets/icons/bin.png
    - assets/icons/Info.png
    - assets/icons/pay.png
    - assets/icons/theme.png
    - assets/icons/privacy.png
    - assets/icons/logout.png
    - assets/icons/lang.png
    - assets/icons/backarrow.png
    - assets/icons/edit.png
    - assets/icons/micoff.png
    - assets/icons/share.png
    - assets/icons/addto.png
    - assets/icons/addtonextqueue.png
    - assets/icons/download.png
    - assets/icons/backwordarrow.png
    - assets/icons/play.png
    - assets/icons/forword.png
    - assets/icons/menu.png
    - assets/icons/down2.png
    - assets/icons/ad.png
    - assets/icons/hd.png
    - assets/icons/facebook.svg
    - assets/icons/twitter.svg
    - assets/icons/linkedin.svg
    - assets/icons/grid.svg
    - assets/icons/list.svg
    - assets/icons/autoplay_icon.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
